server:
  port: 8061
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank_schema
    username: root
    password: Pankaj@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
